const API_BASE=(window.API_BASE||new URLSearchParams(location.search).get('api')||'').replace(/\/$/,'');
let authMode='login';
let activeUser=null;
const $=id=>document.getElementById(id);
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));

function toast(message,type='info'){const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=message;$('toasts').appendChild(el);setTimeout(()=>el.style.opacity='0',2600);setTimeout(()=>el.remove(),3000)}
function showAuthMessage(message,type='error'){const el=$('auth-message');el.textContent=message;el.className=`form-message visible ${type}`}
function clearAuthMessage(){$('auth-message').className='form-message';$('auth-message').textContent=''}
function setAuthMode(mode){authMode=mode;const register=mode==='register';$('login-tab').classList.toggle('active',!register);$('register-tab').classList.toggle('active',register);$('name-field').classList.toggle('hidden',!register);$('confirm-field').classList.toggle('hidden',!register);$('login-options').classList.toggle('hidden',register);$('demo-login').classList.toggle('hidden',register);$('auth-title').textContent=register?'Create your account':'Welcome back';$('auth-subtitle').textContent=register?'Start building your personal learning workspace.':'Sign in to continue your learning journey.';$('auth-submit').textContent=register?'Create account':'Log in';$('auth-password').autocomplete=register?'new-password':'current-password';$('auth-name').required=register;$('auth-confirm').required=register;clearAuthMessage()}
function togglePassword(){const input=$('auth-password');input.type=input.type==='password'?'text':'password';document.querySelector('.password-toggle').textContent=input.type==='password'?'Show':'Hide'}
function readAccounts(){try{return JSON.parse(localStorage.getItem('studybot_accounts')||'{}')}catch{return {}}}
function saveSession(user,persistent=true){const store=persistent?localStorage:sessionStorage;store.setItem('studybot_session',JSON.stringify(user));activeUser=user;openApp()}
function submitAuth(event){event.preventDefault();clearAuthMessage();const name=$('auth-name').value.trim();const email=$('auth-email').value.trim().toLowerCase();const password=$('auth-password').value;const accounts=readAccounts();if(authMode==='register'){if(name.length<2)return showAuthMessage('Please enter your full name.');if(password!==$('auth-confirm').value)return showAuthMessage('Passwords do not match.');if(accounts[email])return showAuthMessage('An account with this email already exists.');accounts[email]={name,email,password};localStorage.setItem('studybot_accounts',JSON.stringify(accounts));showAuthMessage('Account created. You can log in now.','success');setAuthMode('login');$('auth-email').value=email;$('auth-password').value='';return}const account=accounts[email];if(!account||account.password!==password)return showAuthMessage('Email or password is incorrect. Register first or use the demo account.');saveSession({name:account.name,email:account.email},$('remember-me').checked)}
function demoLogin(){saveSession({name:'Demo Student',email:'demo@studybot.local'},false)}
function logout(){localStorage.removeItem('studybot_session');sessionStorage.removeItem('studybot_session');activeUser=null;$('app-view').classList.add('hidden');$('auth-view').classList.remove('hidden');setAuthMode('login');toast('You have been logged out.','info')}
function openApp(){$('auth-view').classList.add('hidden');$('app-view').classList.remove('hidden');const first=activeUser.name.split(/\s+/)[0];$('user-name').textContent=activeUser.name;$('user-email').textContent=activeUser.email;$('user-avatar').textContent=activeUser.name.charAt(0).toUpperCase();$('greeting-name').textContent=first;loadStatus();refreshDocuments();loadQueryCount()}
function restoreSession(){for(const store of [localStorage,sessionStorage]){try{const session=JSON.parse(store.getItem('studybot_session'));if(session?.email){activeUser=session;openApp();return}}catch{}}}
function toggleSidebar(){$('sidebar').classList.toggle('open');$('sidebar-scrim').classList.toggle('open')}
function userId(){return activeUser?.email||'test-user-001'}
function logDebug(label,data){const log=$('debug-log');const previous=log.textContent==='No requests yet.'?'':log.textContent;log.textContent=`── ${new Date().toLocaleTimeString()} — ${label} ──\n${JSON.stringify(data,null,2)}\n\n${previous}`.slice(0,12000)}
async function apiCall(path,options={}){options.headers=Object.assign({'X-User-Id':userId()},options.headers||{});try{const response=await fetch(API_BASE+path,options);const text=await response.text();let body;try{body=JSON.parse(text)}catch{body=text}logDebug(`${options.method||'GET'} ${path}`,body);return {ok:response.ok,status:response.status,body}}catch(error){logDebug(`${options.method||'GET'} ${path}`,{error:error.message});return {ok:false,status:0,body:{detail:'Unable to reach the backend.'}}}}
async function loadStatus(){const result=await apiCall('/health');if(!result.ok){$('status-pills').innerHTML='<span class="status-pill offline"><i class="status-dot"></i>Backend offline</span>';$('backend-state').innerHTML='<i class="status-dot offline"></i> Backend offline';return}const localValues=new Set(['local','sqlite']);$('status-pills').innerHTML=Object.entries(result.body.backends).map(([key,value])=>{const mode=localValues.has(value)?'local':'remote';return `<span class="status-pill ${mode}" title="${escapeHtml(value)}"><i class="status-dot"></i>${escapeHtml(key.toUpperCase())}</span>`}).join('');const isLocal=Object.values(result.body.backends).every(value=>localValues.has(value));$('backend-state').innerHTML=isLocal?'<i class="status-dot local"></i> Local development mode':'<i class="status-dot remote"></i> AWS services connected'}

const drop=$('drop'),fileInput=$('file');
drop.addEventListener('dragover',event=>{event.preventDefault();drop.classList.add('dragover')});drop.addEventListener('dragleave',()=>drop.classList.remove('dragover'));drop.addEventListener('drop',event=>{event.preventDefault();drop.classList.remove('dragover');if(event.dataTransfer.files[0])uploadFile(event.dataTransfer.files[0])});fileInput.addEventListener('change',event=>{if(event.target.files[0])uploadFile(event.target.files[0])});
async function uploadFile(file){const allowed=['pdf','txt','md'];const extension=(file.name.split('.').pop()||'').toLowerCase();if(!allowed.includes(extension))return toast('Only PDF, TXT, and Markdown files are supported.','warn');if(file.size>10*1024*1024)return toast('This file is larger than the recommended 10 MB limit.','warn');$('upload-result').innerHTML=`<div class="upload-success"><i class="spinner"></i> Uploading and indexing <strong>${escapeHtml(file.name)}</strong>…</div>`;const form=new FormData();form.append('file',file);const result=await apiCall('/upload',{method:'POST',body:form});if(!result.ok){$('upload-result').innerHTML=`<div class="upload-error">${escapeHtml(result.body.detail||'Upload failed.')}</div>`;return toast('Upload failed.','error')}const item=result.body;$('upload-result').innerHTML=`<div class="upload-success"><strong>${escapeHtml(item.filename)}</strong> is ready · ${Number(item.chars_extracted||0).toLocaleString()} characters indexed</div>`;toast(`${item.filename} added to your library.`,'success');fileInput.value='';refreshDocuments()}
async function ask(){const question=$('question').value.trim();if(!question)return toast('Enter a question first.','warn');$('ask-btn').disabled=true;$('answer-card').classList.add('visible');$('answer-text').innerHTML='<i class="spinner"></i> Reading your notes…';$('citations').innerHTML='';const result=await apiCall('/query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question})});$('ask-btn').disabled=false;if(!result.ok){$('answer-text').textContent=result.body.detail||'The request failed.';return}$('answer-text').textContent=result.body.answer;const citations=result.body.citations||[];$('citations').innerHTML=citations.length?citations.map((citation,index)=>`<article class="citation"><div class="citation-head"><span>Source ${index+1}</span><span class="score">score ${Number(citation.score||0).toFixed(1)}</span></div><div>${escapeHtml(citation.text||'Source reference')}</div></article>`).join(''):'<div class="citation">No citation matched this answer.</div>';loadQueryCount()}
$('question').addEventListener('keydown',event=>{if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)){event.preventDefault();ask()}});
async function refreshDocuments(){const result=await apiCall('/docs/list');const docs=result.ok&&Array.isArray(result.body.docs)?result.body.docs:[];$('document-count').textContent=docs.length;$('docs').innerHTML=docs.length?docs.map(doc=>`<article class="doc-item"><span class="doc-icon">▤</span><strong title="${escapeHtml(doc.filename||doc.doc_id)}">${escapeHtml(doc.filename||doc.doc_id)}</strong><small>${Number(doc.chars||0).toLocaleString()} characters · ${Number(doc.size||0).toLocaleString()} bytes</small></article>`).join(''):'<div class="empty-state"><strong>Your library is empty</strong><span>Upload a document to start learning.</span></div>'}
async function loadQueryCount(){const result=await apiCall('/queries/recent?limit=100');$('query-count').textContent=result.ok&&Array.isArray(result.body.queries)?result.body.queries.length:0}
restoreSession();
